# Generated by Django 3.0.3 on 2020-08-13 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analogy',
            options={'verbose_name_plural': 'Analogies'},
        ),
    ]
