# Generated by Django 3.0.3 on 2020-08-13 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_ip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IP',
        ),
    ]
